// COUNTRY PREFIX CODES FOR DATA GOING TO OTHER GROUPS
// NOTE THAT THE FIRST LETTER SHOULD BE CAPITALIZED
// TO FIT IN WITH STRING SCHEMA
export const groups = [
	'USA',
	'Mexico',
	'Burning Man',
];
