// COUNTRY PREFIX CODES FOR DATA GOING TO OTHER COUNTRIES
// NOTE THAT THE FIRST LETTER SHOULD BE CAPITALIZED
// TO FIT IN WITH STRING SCHEMA
export const countries = [
	{"USA": 'Usa'},
	{"Mexico": 'Mex'}
]